#!/bin/bash
set -e

# setup-prod.sh
# Gera .env de produção interativamente e executa `docker-compose up --build -d`

print_header(){
  echo
  echo "========================================"
  echo " EDDA - SETUP DE PRODUÇÃO "
  echo "========================================"
  echo
}

command_exists(){ command -v "$1" >/dev/null 2>&1; }

print_header

# Verifica docker e docker-compose
if ! command_exists docker; then
  echo "ERROR: Docker não instalado. Instale o Docker antes de continuar." >&2
  exit 1
fi

if ! command_exists docker-compose; then
  echo "ERROR: docker-compose não instalado. Instale o docker-compose antes de continuar." >&2
  exit 1
fi

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

if [ -f "$ENV_FILE" ]; then
  echo "Arquivo .env já existe. Deseja sobrescrever? (s/N)"
  read -r OVERRIDE
  if [[ ! "$OVERRIDE" =~ ^([sS]|[yY])$ ]]; then
    echo "Mantendo .env existente. Executando docker-compose..."
    docker-compose up --build -d
    exit 0
  fi
fi

# Função para gerar JWT_SECRET
generate_jwt(){
  if command_exists openssl; then
    openssl rand -hex 32
  else
    # fallback para node
    node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
  fi
}

# Ler valores do exemplo quando disponível
get_example_value(){
  local key="$1"
  if [ -f "$EXAMPLE_FILE" ]; then
    grep -E "^${key}=" "$EXAMPLE_FILE" | cut -d'=' -f2- | sed 's/^\s*//;s/\s*$//'
  fi
}

# Prompt genérico
prompt_var(){
  local key="$1"; shift
  local prompt="$1"; shift
  local default="$1"; shift
  local value
  if [ -n "$default" ]; then
    read -p "$prompt [$default]: " value
    value="${value:-$default}"
  else
    read -p "$prompt: " value
  fi
  echo "$value"
}

# Collect values
DB_NAME=$(prompt_var "DB_NAME" "DB name" "${DB_NAME:-$(get_example_value DB_NAME)}")
DB_USER=$(prompt_var "DB_USER" "DB user" "${DB_USER:-$(get_example_value DB_USER)}")

# Password: hide input
read -s -p "DB password (will not be shown): " DB_PASSWORD
echo
if [ -z "$DB_PASSWORD" ]; then
  echo "DB_PASSWORD vazio. Saindo." >&2
  exit 1
fi

# JWT
read -p "Generate secure JWT_SECRET? (recommended) [Y/n]: " gen_jwt
if [[ "$gen_jwt" =~ ^([nN])$ ]]; then
  read -p "JWT_SECRET (paste): " JWT_SECRET
  if [ -z "$JWT_SECRET" ]; then
    echo "JWT_SECRET obrigatório. Saindo." >&2
    exit 1
  fi
else
  JWT_SECRET=$(generate_jwt)
  echo "Generated JWT_SECRET: $JWT_SECRET"
fi

JWT_EXPIRY=$(prompt_var "JWT_EXPIRY" "JWT expiry (ex: 8h)" "8h")
ALLOWED_ORIGINS=$(prompt_var "ALLOWED_ORIGINS" "ALLOWED_ORIGINS (comma-separated)" "${ALLOWED_ORIGINS:-$(get_example_value ALLOWED_ORIGINS)}")
FRONTEND_URL=$(prompt_var "FRONTEND_URL" "FRONTEND_URL" "${FRONTEND_URL:-$(get_example_value FRONTEND_URL)}")
SERVER_BASE_URL=$(prompt_var "SERVER_BASE_URL" "SERVER_BASE_URL" "${SERVER_BASE_URL:-$(get_example_value SERVER_BASE_URL)}")

EMAIL_USER=$(prompt_var "EMAIL_USER" "EMAIL_USER" "${EMAIL_USER:-$(get_example_value EMAIL_USER)}")
read -s -p "EMAIL_APP_PASS (will not be shown): " EMAIL_APP_PASS
echo
if [ -z "$EMAIL_APP_PASS" ]; then
  echo "EMAIL_APP_PASS vazio. Saindo." >&2
  exit 1
fi
EMAIL_FROM=$(prompt_var "EMAIL_FROM" "EMAIL_FROM" "${EMAIL_FROM:-$(get_example_value EMAIL_FROM)}")

DEBUG_MODE=$(prompt_var "DEBUG_MODE" "DEBUG_MODE (true/false)" "false")

# Write .env
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-prod.sh
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=${JWT_EXPIRY}

ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
FRONTEND_URL=${FRONTEND_URL}
SERVER_BASE_URL=${SERVER_BASE_URL}

EMAIL_USER=${EMAIL_USER}
EMAIL_APP_PASS=${EMAIL_APP_PASS}
EMAIL_FROM=${EMAIL_FROM}

DEBUG_MODE=${DEBUG_MODE}
NODE_ENV=production
PORT=3001
EOF

chmod 600 "$ENV_FILE" || true

echo
echo "Arquivo .env criado com sucesso. Conteúdo sensível protegido (chmod 600)."

# Executar docker-compose up --build -d
echo
echo "Executando: docker-compose up --build -d"
docker-compose up --build -d

# Exibir status
sleep 5
echo
docker-compose ps

echo
# Final message
echo "Setup concluído. Verifique logs: docker-compose logs -f backend" 
